### ISSUE TITLE
Я не можу створити нового юзера

### ISSUE THREAD

**Issue by RolandE36** [CH033dotNET/Taxi#11]
http://screencast.com/t/HyAdDn33q0vW

Steps:
1. Взяти останню версію коду і збілдити
2. Створити чисту БД
3. Заранити міграції
4. При створенні юзера отримую помилки.

В БД досі нема ролей. Скоріше за все це і є причиною. Або у вас щось не так з міграціями.

AR: Не можу створити юзера.
ER: Я не повинен мати помилки виконуючи ці степи.

**Comment by dorin157** [comment]
Ролі добавлені, треба лиш зробити "update-database"

**Comment by RolandE36** [comment]
Ок. Тепер все працює.
