### ISSUE TITLE
Не залогінений користувач не повинне бачити меню

### ISSUE THREAD

**Issue by RolandE36** [CH033dotNET/Taxi#12]
http://screencast.com/t/LYiN2N215PyH

Я, мабуть, детально це не описав, але логічно, що не залогінений користвувач не повинен бачити деякі пункти меню.

Якщо ми в URL введемо якийсь шлях і перейдемо на сторінку до якої користувач не має доступу, то перевірка на це буде зроблена пізніше. 

Але показувати/ховати відповідні пункти меню ми можемо вже. В сесії є користувач, в нього є роль і відповідно до ролі треба показувати/ховати пункти меню. Щоб знати які пункти меню треба показувати, просто передивіться на сторі, якщо в них щось сказано про пермішини, то так і робіть.

**Comment by Macsimuse** [comment]
After providing If operator in Base Controler, we can check user Role in View Index threw   Id field
 @if(ViewBag.UserRoleId == (int)AvailableRoles.Administrator) {
                @Html.Partial("_PartialMenuAdmin")
}

**Comment by Macsimuse** [comment]
Roma please check block of code in Layout where I am using IF ELSE 
I think it is better than switch
Also look at Pyramid _PartialMenu views witch encapsulate each other, can I invent this style????

**Comment by RolandE36** [comment]
Для малх проектів твій код нормальний. І притензій до нього в такому випадку нема. Але якщо припустити що проект буде рости, потім появиться куча різних ролей, то буде дуже важко підтримувати такий код. 

Наприклад, в мене на проекті є 12 базових ролей + динамічно можна створювати скільки завгодно своїх власних і надавати їм різні права доступу. В такому випадку варіант коли ми робимо для кожної ролі сласний _PartialMenu - не спрацює.

Тому, в основному Layout-ті дадаєм меню і перед кожним пунктом меню ставимо if (........) і перевіряємо чи цей користувач може бачити цей пункт меню. Спочатку це здаватиметься надлишковим, але з збільшенням коду такий підхід стане простішим.

**Comment by Macsimuse** [comment]
Already done, by If block in Layout
