### ISSUE TITLE
Карта на головній сторінці

### ISSUE THREAD

**Issue by RolandE36** [CH033dotNET/Taxi#13]
http://screencast.com/t/tbqZZZxwjV

Звідкми взялась карта на головній сторінці? Я такого завдання нікому не давав. Треба забрати.

**Comment by dorin157** [comment]
Карту, я добавив, просто не зрозумів в якому форматі треба залити - "Результат роботи завантажити на Wiki в гітхабі"... На даний момент я доробив і вивід міста, вулиці і т.д., але є деякі баги, або навіть можна сказати, "дивне поводження карт", які хотів би обговорити...

**Comment by RolandE36** [comment]
З сайту зараз забери її. Я сьогодні прийду, тоді і поговоримо.
