### ISSUE TITLE
Деякі зміни до додавання "улюблених адрес"

### ISSUE THREAD

**Issue by RolandE36** [CH033dotNET/Taxi#15]
Загалом - все добре зроблено. Лиш треба деякі поля додати і забрати. На картинці описав.

http://screencast.com/t/mUgcaP7s

**Comment by kateminaieva** [comment]
Рома, привіт. З певних обставин я змушена була поїхати з України, зараз
вернулася, але нічого не зробила щоб показати на наступним демо. Будь ласка
дозволь мені працювати далі в проекті але вже з наступного демо. Я обіцяю
виправитись і далі працюватиму старанніше. Вибач за те що сталося.
 Катя ( з SoftServe курсів .NET)

2015-10-03 10:09 GMT+03:00 Roman Lytvyn notifications@github.com:

**Comment by RolandE36** [comment]
Та нема проблем. Лиш я не знаю як ти доганятимеш все... але спробуй.
