### ISSUE TITLE
Поправити пункти меню (в залежності від їх ролей)

### ISSUE THREAD

**Issue by RolandE36** [CH033dotNET/Taxi#16]
Steps:
1. Залогінитись як звичайний користувач

ER (Expected Result): Звичайний користувач може додати до своєї сторінки декалька адрес з яких (на його думку) він найчастіше викликає таксі.
AR (Actual Result): В меню нема такого пункту. Меню взагалі порожнє.

**Comment by Macsimuse** [comment]
Roma can you please check one more time, i have just updated version.
Client can see his personal page. As well when you log in under different Roles, you may see different fields.   About additional function, " the most often used address" 
It doesn't ready yet, so I cannot put this on the page.

**Comment by RolandE36** [comment]
Читай коментар до 12-го багу. Обидва цейсь це одна і та ж проблема, просто з різних сторін.
