### ISSUE TITLE
Усі паролі повинні бути замінені на ***********

### ISSUE THREAD

**Issue by RolandE36** [CH033dotNET/Taxi#4]
http://screencast.com/t/Oil5mxvKIcRy

AR: Пароль не замаскований
ER: Пароль повинен бути замаскованим. Зробіть як тут http://www.w3schools.com/bootstrap/bootstrap_forms.asp

**Comment by Warox23** [comment]
сделано

**Comment by RolandE36** [comment]
Тут ще поправ і тоді буде готово http://localhost:51540/Settings/ChangeMenu/1

**Comment by Warox23** [comment]
готово
