### ISSUE TITLE
Форми не повинні йти в один рядок

### ISSUE THREAD

**Issue by RolandE36** [CH033dotNET/Taxi#5]
http://screencast.com/t/6uypFOn1jBY

Такі форми робили в 90-х. Давайте використовувати бутстрап, щоб все було гарно і читабельно. Зробіть як тут http://www.w3schools.com/bootstrap/bootstrap_forms.asp

**Comment by Warox23** [comment]
вроде таких не осталось уже 
все свои попраивли
